### ISSUE TITLE
解密会话内容的密钥问题

### ISSUE THREAD

**Issue by CSOTD** [wjason/wework-archives#2]
麻烦问下密钥如何获取呢 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/34634945/160524672-4509f0b8-4511-465e-b88b-45e14de9c31f.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/34634945/160525786-318882a3-9e4d-45e4-b31c-224c846036f3.png">
这里只有公钥 没有密钥

**Comment by wjason** [comment]
看企业微信文档，这个是在企业微信那边生成的，拿来解密用的
